name: riverpod_movie_app
description: DDD - Riverpod Movie App 

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  
  cupertino_icons: ^1.0.2
  
  
  flutter:
    sdk: flutter
  
  #Network
  dio: ^4.0.6
  #Route
  auto_route: ^5.0.1
  #State Managment
  flutter_riverpod: ^1.0.3
  riverpod: ^1.0.3+1
  #Object Supports
  freezed_annotation: ^2.1.0
  equatable: ^2.0.5
  #DI
  get_it: ^7.2.0
  #JsonParse
  json_annotation: ^4.7.0
  #Logging
  logger: ^1.1.0
  #.env
  flutter_dotenv: ^5.0.2

dev_dependencies:
  #Generator
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  json_serializable: ^6.4.0
  freezed: ^2.0.5
  #Linter
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:
  assets:
    - .env
  uses-material-design: true
